export const COCKTAIL_LIST_LOADING = "COCKTAIL_LIST_LOADING";
export const COCKTAIL_LIST_SUCCESS = "COCKTAIL_LIST_SUCCESS";
export const COCKTAIL_LIST_FAIL = "COCKTAIL_LIST_FAIL";

export const COCKTAIL_MULTIPULE_LOADING = "COCKTAIL_MULTIPULE_LOADING";
export const COCKTAIL_MULTIPULE_SUCCESS = "COCKTAIL_MULTIPULE_SUCCESS";
export const COCKTAIL_MULTIPULE_FAIL = "COCKTAIL_MULTIPULE_FAIL";

